name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: src
      run: msbuild src.sln
      
    - name: execute
      working-directory: x64/Debug/
      run: src.exe
      
    - name: git setting
      run: |
        git config --local user.email "test@mail.com"
        git config --local user.name "CI"
        git fetch
        git checkout result

    - name: commit result
      run: |
        echo " " >> result.png
        git add result.png
        git commit -m "Add result" -a
        git pull
        git push origin result
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
