name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: git setting
      run: |
        git config --local user.email "test@mail.com"
        git config --local user.name "CI"
        git fetch
        git checkout result
    - name: cd
      run: cd src
#    - name: configure
#      run: ./configure
    - name: make
      run: make
    - name: execute
      run: a.out
    - name: commit result
      run: |
        git add result.png
        git commit -m "Add result" -a
        git pull
        git push origin result
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
