name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Submodules
      run: |
        git config --local user.email "test@mail.com"
        git config --local user.name "CI"
        git fetch

    - name: Dependency - MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
      with:
        vswhere-path: 'C:\Program Files (x86)\Microsoft Visual Studio\Installer'  
      
    - name: MSBuild
      working-directory: src
      continue-on-error: true
      run: |
        msbuild src.sln -p:OutDir="out/" -m

    - name: execute
      working-directory: src
      run: |
        cp out/src.exe ../../
        git checkout result
        ls -r
        ../../src.exe
        cp result.png ../

    - name: commit result
      run: |
        ls -r
        git add result.png
        git commit -m "Add result" -a
        git pull
        git push origin result
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
